# Generated by Django 2.0.5 on 2018-09-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBManager', '0003_auto_20180701_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('databaseName', models.CharField(max_length=255)),
                ('dbcharSet', models.CharField(default='utf-8', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='port',
            field=models.CharField(default=2, max_length=6),
            preserve_default=False,
        ),
    ]
